// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCW10xm_4A_TWnMB-gt0YfZvIxZIywpeJc',
    appId: '1:988356205140:web:94053be30a8853e3812bc1',
    messagingSenderId: '988356205140',
    projectId: 'crudtut-17d8b',
    authDomain: 'crudtut-17d8b.firebaseapp.com',
    storageBucket: 'crudtut-17d8b.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDCKzEWSHfip18_iQ40s9pZYGWti_AJYXo',
    appId: '1:988356205140:android:99a55a79b923f74d812bc1',
    messagingSenderId: '988356205140',
    projectId: 'crudtut-17d8b',
    storageBucket: 'crudtut-17d8b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD72bAjp2oJ202UqwoIx4CNR-8BzReIGFs',
    appId: '1:988356205140:ios:9b97274fd5c65918812bc1',
    messagingSenderId: '988356205140',
    projectId: 'crudtut-17d8b',
    storageBucket: 'crudtut-17d8b.firebasestorage.app',
    iosBundleId: 'com.example.providerLearn',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD72bAjp2oJ202UqwoIx4CNR-8BzReIGFs',
    appId: '1:988356205140:ios:9b97274fd5c65918812bc1',
    messagingSenderId: '988356205140',
    projectId: 'crudtut-17d8b',
    storageBucket: 'crudtut-17d8b.firebasestorage.app',
    iosBundleId: 'com.example.providerLearn',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCW10xm_4A_TWnMB-gt0YfZvIxZIywpeJc',
    appId: '1:988356205140:web:eb1ac0f4d42a4007812bc1',
    messagingSenderId: '988356205140',
    projectId: 'crudtut-17d8b',
    authDomain: 'crudtut-17d8b.firebaseapp.com',
    storageBucket: 'crudtut-17d8b.firebasestorage.app',
  );
}
